auth:
  #Klucz API z panelu yShop (https://yshop.pl/panel/manage/ID_SKLEPU/api)
  apikey: 'eQASSpt18gcxyPVhtlJn23zOE'
  #Nazwa serwera z panelu yShop
  server: 'survival'
  #Adres serwera API. NIE ZMIENIAJ TEJ LINIJKI
  apiurl: 'https://api.yshop.pl/publicapi/'
#Jezeli funkcja jest wlaczona w konsoli beda wyswietlane wiadomosci zwrote z API
debug: true